### ISSUE TITLE
Unbound numeric loops are not supported by OneScript

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-Scripting-Toolkit#4]
This question is currently not supported and will result in an "Out of Memory Error":

`q6 "Have you had to stay overnight in hospital because of side effects?" loop
     fields -
        (
            q6a "Date"
                style(
                        Control(
                                Type="singlelineedit",mask="99-9999",placeholder="MM-YYYY"
                        )
                ) text; 
            q6b "Number of days" long[1..30];
        ) expand grid;`

The workaround is to define the maximum size required for the survey. For example adding `[1..30]`:

`q6 "Have you had to stay overnight in hospital because of side effects?" loop[1..30]
     fields -
        (
            q6a "Date"
                style(
                        Control(
                                Type="singlelineedit",mask="99-9999",placeholder="MM-YYYY"
                        )
                ) text; 
            q6b "Number of days" long[1..30];
        ) expand grid;`

**Comment by onepointpb** [comment]
Now, the below script is showing `invalid CategoryName` error.

`q6 "Have you had to stay overnight in hospital because of side effects?" loop fields - ( q6a "Date" style( Control( Type="singlelineedit",mask="99-9999",placeholder="MM-YYYY" ) ) text; q6b "Number of days" long[1..30]; ) expand grid;`

But the workaround is working fine.
